workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 99
    environment:
      groups:
        - group_name
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
